# Generated by Django 4.1.7 on 2023-04-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_user_details_user_email_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
