# Generated by Django 4.1.7 on 2023-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='some title', max_length=30),
        ),
    ]
