# Generated by Django 4.1.7 on 2023-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='names',
            field=models.CharField(default='some name', max_length=30),
        ),
    ]
