# Generated by Django 4.1.7 on 2023-04-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_review_reviews_review_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='product_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='names',
        ),
    ]
